# Generated by Django 5.0 on 2024-01-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CP', to='Customer.customer')),
            ],
        ),
    ]
