# Generated by Django 5.0 on 2024-01-14 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customer_options'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['Amount'], 'verbose_name_plural': 'Purchase'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CP', to='Customer.customer', verbose_name='Customer'),
        ),
    ]
