# Generated by Django 5.0 on 2024-01-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_department_yoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='student_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='YOE',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
