# Generated by Django 5.0 on 2024-01-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0003_department_student_count_alter_department_yoe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='YOE',
            field=models.IntegerField(default=1990, null=True),
        ),
    ]
