# Generated by Django 5.0 on 2024-02-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_subject_alter_student_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.SmallIntegerField()),
                ('rank', models.SmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdt_report_card', to='University.student')),
            ],
            options={
                'verbose_name_plural': 'Report Card',
                'unique_together': {('total', 'rank', 'date')},
            },
        ),
    ]
