# Generated by Django 5.0 on 2024-02-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0006_report_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
